# roles/mariadb/tasks/config.yml
---

- name: Install server config file
  template:
    src: etc_my.cnf.d_server.cnf.j2
    dest: "{{ mariadb_config_server }}"
    mode: '0640'
    owner: "{{ mariadb_system_user.uid }}"
    group: "{{ mariadb_system_user.gid }}"
  notify: restart mariadb
  tags: mariadb

- name: Install network config file
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: "{{ mariadb_config_network }}"
    mode: '0640'
    owner: "{{ mariadb_system_user.uid }}"
    group: "{{ mariadb_system_user.gid }}"
  notify: restart mariadb
  tags: mariadb

- name: Install custom config file
  template:
    src: etc_my.cnf.d_custom.cnf.j2
    dest: "{{ mariadb_config_custom }}"
    mode: '0640'
    owner: "{{ mariadb_system_user.uid }}"
    group: "{{ mariadb_system_user.gid }}"
  when: mariadb_custom_cnf|length != 0
  notify: restart mariadb
  tags: mariadb

- name: Check if sysctl executable exists. If not, swappiness cannot be set!
  stat:
    path: /usr/sbin/sysctl
  register: sysctl_check

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  when:
    - mariadb_configure_swappiness|bool
    - sysctl_check.stat.exists
  tags: mariadb

# SELinux context mysqld_log_t is default for /var/log/mariadb
- name: Create log directory
  file:
    state: directory
    path: /var/log/mariadb
    owner: mysql
    group: mysql
    mode: '0755'
  when: mariadb_logrotate.configure|bool

- name: Configure logrotate
  template:
    src: etc_logrotate.d_mysql.j2
    dest: /etc/logrotate.d/mysql
    mode: '0644'
  when: mariadb_logrotate.configure|bool
  notify: restart mariadb
  tags: mariadb

- name: Ensure service is started
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
  tags: mariadb
