# roles/mariadb/tasks/config.yml
---

- name: Install server config file
  template:
    src: etc_my.cnf.d_server.cnf.j2
    dest: "{{ mariadb_config_server }}"
  notify: restart mariadb
  tags: mariadb

- name: Install network config file
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: "{{ mariadb_config_network }}"
  notify: restart mariadb
  tags: mariadb

- name: Install custom config file
  template:
    src: etc_my.cnf.d_custom.cnf.j2
    dest: "{{ mariadb_config_custom }}"
  when: mariadb_custom_cnf|length != 0
  notify: restart mariadb
  tags: mariadb

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  when: mariadb_configure_swappiness|bool
  tags: mariadb

# SELinux context mysqld_log_t is default for /var/log/mariadb
- name: Create log directory
  file:
    state: directory
    path: /var/log/mariadb
    owner: mysql
    group: mysql
    mode: 0755
  when: mariadb_logrotate.configure|bool

- name: Configure logrotate
  template:
    src: etc_logrotate.d_mysql.j2
    dest: "{{ mariadb_config_logrotate }}"
  when: mariadb_logrotate.configure|bool
  tags: mariadb

- name: Ensure Galera config file is removed before starting service
  file:
    path: /etc/my.cnf.d/galera.cnf
    state: absent
  when: mariadb_galera_master is defined

- name: Ensure service is started
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
  tags: mariadb
